{% raw %}---
- name: install necessary packages
  apt: name={{ item }} state=present
  with_items:
    - supervisor

- name: create supervisor configuration file
  template:
    src=webapp.conf.j2
    dest=/etc/supervisor/conf.d/{{ site_name }}.conf
  notify:
    - restart supervisor

- name: configure sudo for {{ webapp_username }}
  lineinfile: "dest=/etc/sudoers state=present regexp='^%{{ webapp_username }}' line='%{{ webapp_username }} ALL = (root) NOPASSWD:/usr/bin/supervisorctl restart uwsgi_{{ site_name }}'"

- name: enforce supervisor running state
  service: name=supervisor state=running enabled=yes
{% endraw %}
