{% raw %}---
- name: install necessary packages
  apt: name={{ item }} state=present
  with_items:
    - supervisor

- name: create supervisor configuration file
  template:
    src=webapp.conf.j2
    dest=/etc/supervisor/conf.d/{{ site_name }}.conf
  notify:
    - restart supervisor

- name: enforce supervisor running state
  service: name=supervisor state=running enabled=yes
{% endraw %}
