before_install:
  - sudo apt-get update -qq
  - sudo apt-get install openssh-server

language: python
python:
  - "3.8"

install:
  - pip3 install git+https://github.com/ansible/ansible@devel#egg=ansible

script:
  - ./tests/tests.sh
