---
- hosts: all
  roles:
    - { role: common, tags: common }
    - { role: nginx, tags: nginx }
    - { role: databases, tags: databases }
    - { role: webapp, tags: webapp }
{% if cookiecutter.has_git == "y" %}    - { role: repo,   tags: repo }{% endif %}
{% if cookiecutter.has_supervisor == "y" %}    - { role: supervisor,   tags: supervisor }{% endif %}
{% if cookiecutter.has_redis == "y" %}    - { role: redis ,   tags: redis }{% endif %}
